---
micronaut:
  application:
    name: moneytransfer

---
datasources:
  default:
    url: jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=TRUE
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    autocommit: true
---
jpa:
  default:
    packages-to-scan:
      - 'ru.einster.moneytransfer'
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true